package com.vk.vIRC.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.Sizeable;
import com.vaadin.ui.*;

import java.util.Properties;

/**
 * @author victor.konopelko
 *         Date: 20.09.11
 */
public class BasicView extends AbstractView {

    public static final String brownFox = "The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. ";

    @AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout;
	@AutoGenerated
	private MenuBar menuBar_1;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public BasicView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// verticalLayout_1
		absoluteLayout = buildAbsoluteLayout_1();
		mainLayout.addComponent(absoluteLayout, "top:0.0px;left:0.0px;");

		return mainLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_1() {
		// common part: create layout
		absoluteLayout = new AbsoluteLayout();
		absoluteLayout.setWidth("100.0%");
		absoluteLayout.setHeight("100.0%");
		absoluteLayout.setImmediate(false);
		absoluteLayout.setMargin(false);

		// menuBar_1
		menuBar_1 = new MenuBar();
		menuBar_1.setWidth(100, Sizeable.UNITS_PERCENTAGE);
		menuBar_1.setHeight("25px");
		menuBar_1.setImmediate(false);
		absoluteLayout.addComponent(menuBar_1, "top:0.0px;left:0.0px;bottom:25.0px;");

        // Save reference to individual items so we can add sub-menu items to
        // them
        final MenuBar.MenuItem V_IRC = menuBar_1.addItem("V-IRC", null);
        final MenuBar.MenuItem VIEW = menuBar_1.addItem("View", null);
        final MenuBar.MenuItem SERVER = menuBar_1.addItem("Server", null);
        final MenuBar.MenuItem SETTINGS = menuBar_1.addItem("Settings", null);
        final MenuBar.MenuItem WINDOW = menuBar_1.addItem("Window", null);
        final MenuBar.MenuItem HELP = menuBar_1.addItem("Help", null);


        // Add a horizontal SplitPanel to the lower area
        final HorizontalSplitPanel horiz = new HorizontalSplitPanel();
        horiz.setSplitPosition(15); // percent
        horiz.setWidth(100, Sizeable.UNITS_PERCENTAGE);
        horiz.setHeight(100, Sizeable.UNITS_PERCENTAGE);
        absoluteLayout.addComponent(horiz, "top:25.0px;left:0.0px;");

        VerticalLayout left = new VerticalLayout();
        VerticalLayout right = new VerticalLayout();
        // left component:
        horiz.setFirstComponent(left);
        left.addComponent(new Label(brownFox));

        // right component:
        horiz.setSecondComponent(right);
        right.addComponent(new Label(brownFox));

		return absoluteLayout;
	}

    @Override
    public void setParameters(Properties p) {
        //TODO
    }
}
